export const STORY_TYPES = [
    { value: "romance", label: "Romantic story" },
    { value: "horror", label: "Horror story" },
    { value: "adventure", label: "Adventure story" },
    { value: "history_learning", label: "History learning" },
    { value: "mystery", label: "Mystery / Unsolved" },
    { value: "sci_fi", label: "Science fiction" },
    { value: "fantasy", label: "Fantasy" },
    { value: "dystopia", label: "Dystopian futures" },
    { value: "alt_history", label: "Alternate history" },
    { value: "cozy_mystery", label: "Cozy mystery" },
    { value: "survival", label: "Survival retelling" }
  ] as const;
  
  export const HISTORY_TOPICS: string[] = [
    "How humanity started: from early hominins to Homo sapiens",
    "All human species before Homo sapiens (Denisovans, H. erectus, H. floresiensis)",
    "From Stone Age to Bronze Age: the toolkit revolutions",
    "The Neolithic Revolution: foragers to farmers",
    "Birth of cities: Uruk and the first states",
    "Rise of Ancient Egypt: Narmer to the Pyramid Age",
    "Egypt’s empires: Middle and New Kingdoms",
    "Mesopotamia in full: Sumer, Akkad, Babylon, Assyria",
    "The Indus Valley civilization: grids, trade, and decline",
    "Early China: Xia (debated), Shang, and Zhou foundations",
    "The Persian Empire: Cyrus to Darius and the royal road",
    "The Aegean world: Minoans and Mycenaeans",
    "Greek city-states and the Persian Wars",
    "Athens’ Golden Age and the Peloponnesian War",
    "Alexander the Great and the Hellenistic world",
    "The Roman Republic: birth, glory, and collapse",
    "The Roman Empire: Pax Romana to crisis and reform",
    "Fall of Rome and the rise of Byzantium",
    "The Silk Road: ideas, goods, and empires in motion",
    "Peoples of the Steppe: Scythians, Huns, Turks, and Mongols",
    "The rise of Christianity and the early Church",
    "The Islamic Golden Age: science, cities, and culture",
    "The Vikings: raids, trade, and settlement",
    "Medieval Europe: feudalism, castles, and cathedrals",
    "The Crusades: causes, clashes, and consequences",
    "The Mongol Empire: Genghis to Kublai",
    "West African empires: Ghana, Mali, and Songhai",
    "Southeast Asian splendor: Angkor and its water empire",
    "The Maya: astronomy, cities, and collapse",
    "The Aztec Empire: rise of Tenochtitlan",
    "The Inca Empire: roads, quipu, and mountains",
    "The Black Death and how it reshaped the world",
    "The Ottoman Empire: rise, systems, and frontiers",
    "The Renaissance: from Florence to the north",
    "The Age of Exploration: oceans, maps, and empires",
    "The Reformation and the wars of religion",
    "The Scientific Revolution: a new way of knowing",
    "The Mughal Empire: art, power, and diversity",
    "Tokugawa Japan: peace, samurai, and isolation",
    "The Qing dynasty: expansion, commerce, and encounter",
    "The Enlightenment: ideas that changed politics and society",
    "The American Revolution and a new republic",
    "The French Revolution and the age of Napoleon",
    "The Industrial Revolution: steam, factories, and cities",
    "Unifications of Italy and Germany: making nations",
    "The British Empire at its height",
    "The Meiji Restoration: Japan’s rapid transformation",
    "The Russian Empire to the 1917 Revolution",
    "World War I: from Sarajevo to the Armistice",
    "The interwar years: upheavals and experiments",
    "World War II: global war and its aftermath",
    "The Cold War: superpowers, spies, and proxy wars",
    "Decolonization: Africa and Asia reshape the world",
    "The Space Race: from Sputnik to the Moon",
    "Yugoslavia: from medieval lands to a 20th-century state",
  
    "Out of Africa and the peopling of the world",
    "Ice Age megafauna and human hunters",
    "The invention of writing: cuneiform, hieroglyphs, and early scripts",
    "Bronze to Iron Age: new metals, new empires",
    "Carthage and the Punic Wars against Rome",
    "Hellenistic science and learning: Alexandria to Archimedes",
    "Second Temple world: Judaism and the classical Mediterranean",
    "Byzantium across a thousand years: Justinian to Basil II",
    "Rise of the Slavs and the early medieval Balkans",
    "Kievan Rus and the birth of Eastern Slavic states",
    "Al-Andalus: convivencia and conflict in Iberia",
    "The Crusader States and the medieval Levant",
    "The Hanseatic League and the rise of northern trade",
    "Knights, chivalry, and the code of medieval war",
    "Gothic cathedrals and the engineers of faith",
    "The Hundred Years’ War: England and France in conflict",
    "Italian city-states and the birth of modern finance",
    "The printing revolution and the spread of ideas",
    "Age of Sail: galleons, pirates, and global navies",
    "The Dutch Golden Age and world trade networks",
    "The Atlantic slave trade and the road to emancipation",
    "Mathematics and astronomy from Babylon to Newton",
    "The Ottoman–Habsburg frontier: centuries of rivalry",
    "Early modern India: Mughals, Marathas, and the Deccan",
    "Qing China and Tokugawa Japan: the Canton system and Nagasaki",
    "The Great Game: Russia and Britain in Central Asia",
    "The Victorian age: industry, empire, and everyday life",
    "The Balkans in the 19th century: nationalism and empire",
    "The Habsburg Monarchy: Vienna, diversity, and decline",
    "The Ottoman Balkans: coexistence, reform, and revolt",
    "The Italian Wars and the birth of modern warfare",
    "Central Europe’s Reformation and Counter-Reformation",
    "China’s Warring States and the Qin unification",
    "The Three Kingdoms era and the making of a legend",
    "Korea from Three Kingdoms to the Joseon dynasty",
    "Vietnam through the ages: Champa, Dai Viet, and mandarins",
    "Indonesia’s maritime empires: Srivijaya to Majapahit",
    "Aksum and the Ethiopian highlands across millennia",
    "The Swahili Coast: monsoon trade cities of East Africa",
    "Polynesian voyaging and the settlement of the Pacific",
    "First Australians: deep time and the Dreaming",
    "North America’s mound builders: Poverty Point to Cahokia",
    "The Iroquois Confederacy and the Great Law of Peace",
    "The Spanish conquest and the Columbian Exchange",
    "Silver empires: Potosí, Manila galleons, and global trade",
    "The Enlightenment coffeehouse and the public sphere",
    "The age of revolutions: 1776–1848 reshaping the world",
    "Industrialization beyond Europe: Russia, Japan, and others",
    "Railways that changed the world",
    "History of banking and paper money",
    "History of maps and exploration",
    "History of timekeeping: calendars and clocks",
    "History of food: spices, sugar, and the global kitchen",
    "History of medicine: from humors to germ theory",
    "Science and mathematics in the Islamic world",
    "Everyday life through the ages: homes, work, and leisure",
    "History of warfare: from chariots to tanks",
    "Naval history: triremes to dreadnoughts",
    "Rise of nationalism in 19th-century Europe",
    "Colonial Latin America: silver, missions, and cities",
    "The American West: frontiers, railroads, and nation-building",
    "China in the 19th century: Opium Wars to self-strengthening",
    "Japan’s road to empire: 1895–1945",
    "India’s long road to independence (pre-1947)",
    "Africa under colonial rule: resistance and change (1880–1960)",
    "The Middle East in the Ottoman twilight: reform and revolt",
    "Spaceflight before Apollo: Goddard, Korolev, and Gagarin",
    "Computing from abacuses to early computers (pre-2000)",
    "Globalization 1850–2000: steam, cables, and containers",
    "Environmental history: the Little Ice Age to industry",
    "History of education: schools, universities, literacy",
    "Law and justice: from ancient codes to constitutions",
    "Philosophy’s long arc: Axial Age to modernity",
    "Art through time: from cave walls to modern museums",
    "Architecture through time: pyramids to skyscrapers",
    "Music through time: chant, classical, and jazz",
    "Sports and games: from antiquity to modern stadiums",
    "Great migrations: waves that shaped civilizations"
  ];
  
  